# Generated by Django 4.2.4 on 2023-08-05 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotareas',
            name='id',
        ),
        migrations.AlterField(
            model_name='registrotareas',
            name='fvencimiento_tarea',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='registrotareas',
            name='id_tarea',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
