# Generated by Django 4.2.4 on 2023-08-05 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_remove_registrotareas_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotareas',
            name='fvencimiento_tarea',
            field=models.DateField(verbose_name=datetime.date(2023, 8, 4)),
        ),
    ]
