# Generated by Django 4.2.4 on 2023-08-05 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_registrotareas_fvencimiento_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotareas',
            name='fvencimiento_tarea',
        ),
        migrations.AddField(
            model_name='registrotareas',
            name='fecha_vencimiento_tarea',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
