# Generated by Django 4.2.4 on 2023-08-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_remove_registrotareas_fvencimiento_tarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotareas',
            name='id_tarea',
            field=models.AutoField(auto_created=True, default=100, max_length=3, primary_key=True, serialize=False),
        ),
    ]
