# Generated by Django 4.2.4 on 2023-08-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_registrotareas_id_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotareas',
            name='id_tarea',
            field=models.AutoField(auto_created=True, default=100, primary_key=True, serialize=False),
        ),
    ]
