# Generated by Django 4.2.4 on 2023-08-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_alter_registrotareas_id_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotareas',
            name='id_tarea',
            field=models.CharField(default='100', max_length=3, primary_key=True, serialize=False),
        ),
    ]
