# Generated by Django 4.2.4 on 2023-08-09 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_registrotareas_id_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotareas',
            name='categoria_tarea',
            field=models.CharField(choices=[('1', 'Trabajo'), ('2', 'Hogar'), ('3', 'Estudio'), ('4', 'Otras categorías')], default='1', max_length=1, verbose_name='Categoria tarea'),
        ),
        migrations.AlterField(
            model_name='registrotareas',
            name='descripcion_tarea',
            field=models.CharField(max_length=150, verbose_name='Descripción de la tarea'),
        ),
        migrations.AlterField(
            model_name='registrotareas',
            name='estado_tarea',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'En progreso'), ('3', 'Completada')], default='1', max_length=1, verbose_name='Estado de la tarea'),
        ),
        migrations.AlterField(
            model_name='registrotareas',
            name='fecha_vencimiento_tarea',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de vencimiento de la tarea'),
        ),
        migrations.AlterField(
            model_name='registrotareas',
            name='titulo_tarea',
            field=models.CharField(max_length=50, verbose_name='Título de la tarea'),
        ),
    ]
