# Generated by Django 4.2.4 on 2023-08-10 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_alter_registrotareas_categoria_tarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotareas',
            name='fecha_vencimiento_tarea',
            field=models.DateField(default=datetime.date(2023, 8, 10), verbose_name='Fecha de vencimiento de la tarea'),
        ),
    ]
